# site name
prefixName: 巫女Sueyoki
siteName: の森林
author: Sueyoki
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.png
url: https://Sueyoki.github.io #这里改自己域名
description: 寒鸦向暖，枯木逢春~
cdn: https://cdn.jsdelivr.net/gh/Sueyoki/CDN@master
pjax: 1
# 1开启
mathjax: 0

notice: 女孩子要狡猾一点才可爱~
lazyloadImg: https://cdn.jsdelivr.net/gh/Sueyoki/CDN@1.3/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    #图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  客户端: { path: /client/, fa: fa-android faa-vertical }
  #RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/Sueyoki/CDN@1.2/img/cover/(1).jpg.webp
  - https://cdn.jsdelivr.net/gh/Sueyoki/CDN@1.2/img/cover/(2).jpg.webp
  - https://cdn.jsdelivr.net/gh/Sueyoki/CDN@1.2/img/cover/(10).jpg.webp
  - https://cdn.jsdelivr.net/gh/Sueyoki/CDN@1.2/img/cover/(4).jpg.webp
  - https://cdn.jsdelivr.net/gh/Sueyoki/CDN@1.2/img/cover/(14).jpg.webp
  - https://cdn.jsdelivr.net/gh/Sueyoki/CDN@1.2/img/cover/(6).jpg.webp
  - https://cdn.jsdelivr.net/gh/Sueyoki/CDN@1.2/img/cover/(7).jpg.webp
  - https://cdn.jsdelivr.net/gh/Sueyoki/CDN@1.2/img/cover/(8).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/SAO.png}
  - {url: https://space.bilibili.com/13588223, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: Sueyoki的森林小屋, desc: 技术服务, img: /img/startdash/1.png}



# your site build time or founded date
siteBuildingTime: 07/17/2020

#social  url, img PC端配置
social:
  github: {url: http://github.com/Sueyoki, img: /img/social/github.png}
  #sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=2112645873, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/su-yuan-qi-98, img: /img/social/zhihu.png}
  #email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
  #qq: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/qq.png}
  #qq: {url: /#, qrcode: /img/custom/qq.jpg, img: /img/social/qq.png}
  wechat: {url: /#, qrcode: /img/custom/qq.jpg, img: /img/social/qq.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/honjun, fa: fa-github, color: 333}
  #weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  #paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  #url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  url: https://cdn.jsdelivr.net/gh/Sueyoki/CDN@master/video
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: 8.mp4,1.mp4,4.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

